/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pixar-v1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pixar-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Pixar_Ball_yellow_with_red_star_0.geometry} material={materials.yellow_with_red_star} position={[0, 100, 0]} rotation={[-0.65, 0.14, 0.11]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/pixar-v1-transformed.glb')
